using System;
using System.Collections.Generic;
using System.Linq;
using Nebulator.Common;


namespace Nebulator.Midi
{
    /// <summary>
    /// Base class for internal interface representation of a compiled event to be sent as midi.
    /// It has some extra functionality not supported by the NAudio MidiEvent.
    /// </summary>
    public abstract class Step
    {
        /// <summary>Name of the parent/owner track.</summary>
        public string TrackName { get; set; } = null;

        /// <summary>Channel.</summary>
        public int Channel { get; set; } = 1;

        /// <summary>
        /// Possibly make adjustments to values.
        /// </summary>
        public virtual void Adjust(int masterVolume, int trackVolume, int modulate) { }

        /// <summary>For viewing pleasure.</summary>
        public override string ToString()
        {
            return $"Channel:{Channel}";
        }
    }

    public class StepNoteOn : Step
    {
        /// <summary>The default note.</summary>
        public int NoteNumber { get; set; } = 60;

        /// <summary>The possibly modified NoteNumber.</summary>
        public int NoteNumberToPlay { get; set; } = 60;

        /// <summary>The default volume.</summary>
        public int Velocity { get; set; } = 90;

        /// <summary>The possibly modified Volume.</summary>
        public int VelocityToPlay { get; set; } = 90;

        /// <summary>Time between note on/off. Default of 0 indicates note off generated by owner.</summary>
        public Time Duration { get; set; } = new Time(0);

        /// <summary>
        /// Possibly make adjustments to values.
        /// </summary>
        public override void Adjust(int masterVolume, int trackVolume, int modulate)
        {
            // Maybe alter note velocity.
            int vel = Velocity * trackVolume * masterVolume / MidiInterface.MAX_MIDI_VOLUME / MidiInterface.MAX_MIDI_VOLUME;
            VelocityToPlay = Utils.Constrain(vel, 0, MidiInterface.MAX_MIDI_VOLUME);

            // Maybe alter note number.
            NoteNumberToPlay = Utils.Constrain(NoteNumber + modulate, 0, MidiInterface.MAX_MIDI_NOTE);
        }

        /// <summary>For viewing pleasure.</summary>
        public override string ToString()
        {
            return $"StepNoteOn: {base.ToString()} NoteNumberToPlay:{NoteNumberToPlay} VelocityToPlay:{VelocityToPlay} Duration:{Duration}";
        }
    }

    public class StepNoteOff : Step
    {
        /// <summary>The default note.</summary>
        public int NoteNumber { get; set; } = 60;

        /// <summary>The possibly modified NoteNumber.</summary>
        public int NoteNumberToPlay { get; set; } = 60;

        /// <summary>Velocity.</summary>
        public int Velocity { get; set; } = 64; // seems to be standard default.

        /// <summary>When it's done in tocks - used by stop note tracking.</summary>
        public int Expiry { get; set; } = -1;

        /// <summary>Constructor to make a deferred note off from a note on.</summary>
        /// <param name="step"></param>
        public StepNoteOff(StepNoteOn step)
        {
            TrackName = step.TrackName;
            Channel = step.Channel;
            NoteNumber = Utils.Constrain(step.NoteNumber, 0, MidiInterface.MAX_MIDI_NOTE);
            NoteNumberToPlay = step.NoteNumberToPlay;
            Expiry = step.Duration.TotalTocks;
        }

        /// <summary>Default constructor.</summary>
        public StepNoteOff()
        {
        }

        /// <summary>
        /// Possibly make adjustments to values.
        /// </summary>
        public override void Adjust(int masterVolume, int trackVolume, int modulate)
        {
            // Maybe alter note number.
            NoteNumberToPlay = Utils.Constrain(NoteNumber + modulate, 0, MidiInterface.MAX_MIDI_NOTE);
        }

        /// <summary>For viewing pleasure.</summary>
        public override string ToString()
        {
            return $"StepNoteOff: {base.ToString()} NoteNumberToPlay:{NoteNumberToPlay}";
        }
    }

    public class StepControllerChange : Step
    {
        /// <summary>Specific controller.</summary>
        public int MidiController { get; set; } = MidiInterface.CTRL_NONE;

        /// <summary>The midi payload. Also used for Pitch.</summary>
        public int ControllerValue { get; set; } = 0;

        /// <summary>For viewing pleasure.</summary>
        public override string ToString()
        {
            return $"StepControllerChange: {base.ToString()} Controller:{ControllerValue}";
        }
    }

    public class StepPatch : Step
    {
        /// <summary>Specific patch.</summary>
        public int PatchNumber { get; set; } = 0;

        /// <summary>For viewing pleasure.</summary>
        public override string ToString()
        {
            return $"StepPatchChange: {base.ToString()} PatchNumber:{PatchNumber}";
        }
    }
}
